version: "3.9"

services:
  backend:
    image: node:22-alpine
    container_name: backend

    working_dir: /app

    ports:
      - "3000:3000"

    volumes:
      - ./backend:/app

    stdin_open: true
    tty: true

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_started

    networks:
      - backend-network

  postgres:
    image: postgres:17
    container_name: postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: backenddb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d backenddb"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - backend-network

  redis:
    image: redis:8
    container_name: redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    networks:
      - backend-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin

    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "5050:80"

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - pgadmin-data:/var/lib/pgadmin

    networks:
      - backend-network

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle

    restart: unless-stopped

    ports:
      - "8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  pgadmin-data:
